server {
    listen 9090;
    host "127.0.0.1";
    max_body_size 1048576;

    error_page 400 ./var/errors/400.html;
    error_page 401 ./var/errors/401.html;
    error_page 403 ./var/errors/403.html;
    error_page 404 ./var/errors/404.html;
    error_page 405 ./var/errors/405.html;
    error_page 408 ./var/errors/408.html;
    error_page 411 ./var/errors/411.html;
    error_page 413 ./var/errors/413.html;
    error_page 414 ./var/errors/414.html;
    error_page 415 ./var/errors/415.html;
    error_page 500 ./var/errors/500.html;
    error_page 501 ./var/errors/501.html;
    error_page 502 ./var/errors/502.html;
    error_page 503 ./var/errors/503.html;
    error_page 504 ./var/errors/504.html;
    error_page 505 ./var/errors/505.html;


    location /home {
        methods GET;
        redirect /;
    }
    location / {
        root ./var/www/html;
        index index.html;
        methods GET POST HEAD;
        directory_listing off;
        upload_store ./var/uploads;
    }

    location /upload {
        root ./var/uploads;
        methods POST DELETE GET;
        directory_listing on;
        upload_store ./var/uploads;
    }

    location /inception{
        root ./var/www/html/inception;
        index index.html;
        methods GET;
        directory_listing off;

    }

    location /tester{
        root ./var/www/html/tester;
        index index.html;
        methods GET;
    }

    location /urlencoded {
        root ./var/uploads/urlencoded;
        methods POST DELETE GET;
        upload_store ./var/uploads/urlencoded;
        directory_listing on;
    }

    location /json {
        root ./var/uploads/json;
        methods POST DELETE GET;
        upload_store ./var/uploads/json;
        directory_listing on;
    }
    location /text {
        root ./var/uploads/text;
        methods POST DELETE GET;
        upload_store ./var/uploads/text;
        directory_listing on;
    }

    location /cgi-bin {
        root ./var/www/cgi-bin;
        methods GET POST;
        cgi .php /usr/bin/php-cgi;
    }
}


server {
    listen 5040;
    host "127.0.0.1";
    max_body_size 1048576;


    error_page 400 ./var/errors/400.html;
    error_page 401 ./var/errors/401.html;
    error_page 403 ./var/errors/403.html;
    error_page 404 ./var/errors/404.html;
    error_page 405 ./var/errors/405.html;
    error_page 408 ./var/errors/408.html;
    error_page 411 ./var/errors/411.html;
    error_page 413 ./var/errors/413.html;
    error_page 414 ./var/errors/414.html;
    error_page 415 ./var/errors/415.html;
    error_page 500 ./var/errors/500.html;
    error_page 501 ./var/errors/501.html;
    error_page 502 ./var/errors/502.html;
    error_page 503 ./var/errors/503.html;
    error_page 504 ./var/errors/504.html;
    error_page 505 ./var/errors/505.html;


    location / {
        root ./var/www/html;
        index index.html;
        methods GET ;
    }

    location /home {
        methods GET;
        redirect /;
    }

    location /inception{
        root ./var/www/html/inception;
        index index.html;
        methods GET;
    }

    location /cgi-bin {
        root ./var/www/cgi-bin;
        methods GET POST;
        cgi .php /usr/bin/php-cgi;
    }
}